# Generated by Django 3.1.5 on 2021-02-14 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
